apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec: 
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: ~
  selector:
    matchLabels:
      name: dnsmasq
  template:
    metadata:
      labels:
        name: dnsmasq
      annotations:
        checksum/attributes: {{ .Values | toString | sha256sum }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: dnsmasq
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          args:
              - --no-daemon
              - --no-hosts
              - --no-resolv
              - --port=0
              - --domain={{ .Values.dnsmasq.domain }}
              {{- if .Values.dnsmasq.gateway }}
              - --dhcp-option=3,{{ .Values.dnsmasq.gateway }}
              {{- end }}
              - --dhcp-range={{ .Values.dnsmasq.range }}
              - --enable-tftp
              - --tftp-root=/var/lib/tftpboot
              - --dhcp-match=set:bios,option:client-arch,0
              - --dhcp-boot=tag:bios,undionly.kpxe
              - --dhcp-match=set:efi32,option:client-arch,6
              - --dhcp-boot=tag:efi32,ipxe.efi
              - --dhcp-match=set:efibc,option:client-arch,7
              - --dhcp-boot=tag:efibc,ipxe.efi
              - --dhcp-match=set:efi64,option:client-arch,9
              - --dhcp-boot=tag:efi64,ipxe.efi
              - --dhcp-userclass=set:ipxe,iPXE
              - --dhcp-boot=tag:ipxe,{{ .Values.dnsmasq.ipxeBootUrl }}
              - --dhcp-broadcast
              - --log-queries
              - --log-dhcp
              {{- range .Values.dnsmasq.addresses }}
              - --address={{ . }}
              {{- end }}
              {{- range .Values.dnsmasq.dns }}
              - --server={{ . }}
              {{- end }}
              {{- range .Values.dnsmasq.dhcpHosts }}
              - --dhcp-host={{ . }}
              {{- end }}

          ports:
            - name: dhcp
              containerPort: 67
              port: 67
              protocol: UDP

            - name: tftp
              containerPort: 69
              port: 69
              protocol: UDP
