apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ .Release.Name }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}

  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    {{- if .Values.service.httpNodePort }}
    nodePort: {{ .Values.service.httpNodePort }}
    {{- end }}
