kind: Service
apiVersion: v1
metadata:
  name: {{ template "unbound.fullname" . }}-tcp
  labels:
    app: {{ template "unbound.name" . }}
    chart: {{ template "unbound.chart" . }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: "{{ .Values.service.type }}"
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
  selector:
    app: {{ template "unbound.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: dns-tcp
    protocol: TCP
    port: {{ .Values.unbound.serverPort }}
    targetPort: dns-tcp
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "unbound.fullname" . }}-udp
  labels:
    app: {{ template "unbound.name" . }}
    chart: {{ template "unbound.chart" . }}
    release: {{ .Release.Name  }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: "{{ .Values.service.type }}"
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
  selector:
    app: {{ template "unbound.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: dns-udp
    protocol: UDP
    port: {{ .Values.unbound.serverPort }}
    targetPort: dns-udp
