apiVersion: v1
kind: List
items:
{{- range $name, $content := .Values.secrets }}
- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ $name | quote }}
  type: {{ default "Opaque" $content.type }}
  data:
    {{- range $key, $val := $content.data }}
    {{ $key }}: {{ $val | b64enc }}
    {{- end }}
{{- end }}
