apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: gitserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |
                #!/bin/bash
                cd /data
                {{- range .repositories }}
                if [ ! -d "{{.}}" ]; then
                  git init --bare {{.}}
                  chown -r git: {{.}}
                fi
                {{- end }}
        ports:
          - name: ssh
            containerPort: 22
        volumeMounts:
        - name: config
          mountPath: /home/git/.ssh/
        - name: data
          mountPath: /data
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-data
