apiVersion: v1
kind: Service
metadata:
  name: matchbox
spec:
  type: {{ .Values.service.type }}
  selector:
    name: matchbox
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      {{- if .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
