image:
  repository: n0rad/alpine-gitserver
  tag: latest
  pullPolicy: IfNotPresent

# init repositories if not exists yet
repositories:
# - charts

existingSecret: false
# authorized keys to repos
authorized_keys:
# - 

# ssh-keygen -f ./ssh_host_ecdsa_key -N '' -t ecdsa -b 521
ssh:
  ssh_host_ecdsa_key: ""
  ssh_host_ecdsa_key_pub: ""


service:
  type: ClusterIP
  port: 22
  annotations: {}
  labels: {}
  loadBalancerIP:

persistence:
  storageClass: ""
  size: 20Gi
  accessMode: ReadWriteOnce

resources: {}
