apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ .Release.Name }}
  ports:
    - name: dhcp
      protocol: UDP
      port: 67
      targetPort: 67
    - name: tftp
      protocol: UDP
      port: 69
      targetPort: 69

