apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-ssh
  labels:
    app: {{ template "name" . }}
data:
  ssh_host_ecdsa_key: |
    {{- .Values.ssh.ssh_host_ecdsa_key | b64enc | nindent 4 }}
  ssh_host_ecdsa_key.pub: |
    {{- .Values.ssh.ssh_host_ecdsa_key_pub | b64enc | nindent 4 }}
